language: python

sudo: false

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes --all
    - travis_retry conda env create -f envs/supervisor.yml
    - travis_retry conda env create -f envs/py35.yml
    - source activate supervisor

script:
    - rm -rf services/test
    - cp -R template_service services/test
    - supervisord
    - supervisorctl start all
    - supervisorctl restart all
    - curl http://localhost:8001/test/foo
    - supervisorctl shutdown
    - find . -type f -name "*.py" ! -name 'conf.py' | xargs flake8 --max-line-length=100
