language: python

sudo: false

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes --all
    - travis_retry conda create --yes -n supervisorenv python=2.7
    - source activate supervisorenv

script:
    - find . -type f -name "*.py" ! -name 'conf.py' | xargs flake8 --max-line-length=100

